/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false .wrangler/worker-configuration.generated.d.ts` (hash: e671742c1966cce5b4054e544007a1e4)
interface __BaseEnv_Env {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	ENTRA_CLIENT_ID: "147a13c9-2a9e-4e32-aa01-3f020d2a18cd";
	ENTRA_TENANT_ID: "15c1eb19-1f38-4a09-bb25-7ff9892387b8";
	ENTRA_REDIRECT_URI: "https://corpuskit.noice.net.au/auth/callback";
	PORTAL: DurableObjectNamespace /* PortalDurableObject */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: unknown;
		durableNamespaces: "PortalDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ENTRA_CLIENT_ID" | "ENTRA_TENANT_ID" | "ENTRA_REDIRECT_URI">> {}
}
